{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from Bio import Entrez\n",
    "import os\n",
    "import re\n",
    "import os.path as osp\n",
    "import logging\n",
    "import traceback\n",
    "import pandas as pd\n",
    "from bs4 import BeautifulSoup\n",
    "%run utils/logging.py\n",
    "%run env.py\n",
    "#Entrez.email = 'eric@hammerlab.org'\n",
    "Entrez.email = 'eczech52@gmail.com'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def search(query, retstart=0, retmax=1000):\n",
    "    handle = Entrez.esearch(db='pmc', \n",
    "                            sort='relevance', \n",
    "                            retmax=str(retmax),\n",
    "                            retstart=str(retstart),\n",
    "                            retmode='xml', \n",
    "                            term=query)\n",
    "    results = Entrez.read(handle)\n",
    "    return results\n",
    "\n",
    "def fetch_details(id_list):\n",
    "    ids = ','.join(id_list)\n",
    "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
    "    return handle.read()\n",
    "\n",
    "def parse(soup):\n",
    "    res = {}\n",
    "    res['id'] = [t for t in soup.find('article-meta').find_all('article-id') if t['pub-id-type'] == 'pmc'][0].text\n",
    "    res['title'] = soup.find('title-group').find('article-title').text\n",
    "    res['xml'] = str(soup)\n",
    "    \n",
    "    try:\n",
    "        res['abstract'] = soup.find('abstract').text\n",
    "    except:\n",
    "        res['abstract'] = None\n",
    "    \n",
    "    try:\n",
    "        res['has_text'] = len(soup.find('body').text.strip()) > 0\n",
    "    except:\n",
    "        res['has_text'] = False\n",
    "        \n",
    "    try:\n",
    "        date = [t for t in soup.find('history').find_all('date') if t['date-type'] == 'received'][0]\n",
    "        res['date'] = pd.to_datetime('{}-{}-{}'.format(\n",
    "            date.find('year').text,\n",
    "            date.find('month').text if date.find('month') else '00',\n",
    "            date.find('day').text if date.find('day') else '00'\n",
    "        ))\n",
    "    except:\n",
    "        res['date'] = None\n",
    "    return res\n",
    "\n",
    "def to_df(dets):\n",
    "    soup = BeautifulSoup(dets, 'xml')\n",
    "    return pd.DataFrame([parse(article) for article in soup.find_all('article')])\n",
    "\n",
    "def collect(query, output_file, start_index=0, batch_size=100, batch_limit=None, max_failures=5):\n",
    "    i = start_index\n",
    "    ct = 0\n",
    "    failures = 0\n",
    "    if not osp.exists(osp.dirname(output_file)):\n",
    "        os.makedirs(osp.dirname(output_file))\n",
    "    while True:\n",
    "        try:\n",
    "            ids = search(query, retstart=i, retmax=batch_size)['IdList']\n",
    "            if len(ids) == 0:\n",
    "                break\n",
    "            logger.info('Processing batch at start index {} (num ids = {})'.format(i, len(ids)))\n",
    "            dets = fetch_details(ids)\n",
    "            df = to_df(dets)\n",
    "            df.to_csv(output_file, index=False, header=not osp.exists(output_file), mode='a')\n",
    "            ct += 1\n",
    "            i += batch_size\n",
    "            if batch_limit and ct >= batch_limit:\n",
    "                break\n",
    "        except:\n",
    "            traceback.print_exc()\n",
    "            failures += 1\n",
    "            if failures > max_failures:\n",
    "                raise ValueError('Max failure threshold ({}) exceeded'.format(max_failures))\n",
    "            logger.warning('Error occurred at index {}. Will retry up to {} times'.format(i, max_failures))\n",
    "    logger.info('Collection complete (num failures = {})'.format(failures))\n",
    "            "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# # https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=6089340\n",
    "# dets = fetch_details(['6089340', '212403'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# from bs4 import BeautifulSoup\n",
    "# soup = BeautifulSoup(dets, 'xml')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-03-14 10:43:48,565:INFO:root: Processing batch at start index 0 (num ids = 10)\n",
      "2019-03-14 10:43:51,818:INFO:root: Processing batch at start index 10 (num ids = 10)\n",
      "2019-03-14 10:43:56,353:INFO:root: Processing batch at start index 20 (num ids = 10)\n",
      "2019-03-14 10:44:01,841:INFO:root: Processing batch at start index 30 (num ids = 10)\n",
      "2019-03-14 10:44:04,812:INFO:root: Processing batch at start index 40 (num ids = 10)\n",
      "2019-03-14 10:44:12,635:INFO:root: Processing batch at start index 50 (num ids = 10)\n",
      "2019-03-14 10:44:18,281:INFO:root: Processing batch at start index 60 (num ids = 10)\n",
      "2019-03-14 10:44:22,010:INFO:root: Processing batch at start index 70 (num ids = 10)\n",
      "2019-03-14 10:44:25,185:INFO:root: Processing batch at start index 80 (num ids = 10)\n",
      "2019-03-14 10:44:31,267:INFO:root: Processing batch at start index 90 (num ids = 10)\n",
      "2019-03-14 10:44:39,867:INFO:root: Processing batch at start index 100 (num ids = 10)\n",
      "2019-03-14 10:44:42,943:INFO:root: Processing batch at start index 110 (num ids = 10)\n",
      "2019-03-14 10:44:49,911:INFO:root: Processing batch at start index 120 (num ids = 10)\n",
      "2019-03-14 10:44:53,943:INFO:root: Processing batch at start index 130 (num ids = 10)\n",
      "2019-03-14 10:45:02,030:INFO:root: Processing batch at start index 140 (num ids = 10)\n",
      "2019-03-14 10:45:06,000:INFO:root: Processing batch at start index 150 (num ids = 10)\n",
      "2019-03-14 10:45:32,340:INFO:root: Processing batch at start index 160 (num ids = 10)\n",
      "2019-03-14 10:45:39,956:INFO:root: Processing batch at start index 170 (num ids = 10)\n",
      "2019-03-14 10:45:45,553:INFO:root: Processing batch at start index 180 (num ids = 10)\n",
      "2019-03-14 10:45:52,618:INFO:root: Processing batch at start index 190 (num ids = 10)\n",
      "2019-03-14 10:45:56,131:INFO:root: Processing batch at start index 200 (num ids = 10)\n",
      "2019-03-14 10:46:03,985:INFO:root: Processing batch at start index 210 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:46:34,333:WARNING:root: Error occurred at index 210. Will retry up to 1000000 times\n",
      "2019-03-14 10:46:35,624:INFO:root: Processing batch at start index 210 (num ids = 10)\n",
      "2019-03-14 10:46:43,920:INFO:root: Processing batch at start index 220 (num ids = 10)\n",
      "2019-03-14 10:46:47,031:INFO:root: Processing batch at start index 230 (num ids = 10)\n",
      "2019-03-14 10:46:53,749:INFO:root: Processing batch at start index 240 (num ids = 10)\n",
      "2019-03-14 10:46:58,091:INFO:root: Processing batch at start index 250 (num ids = 10)\n",
      "2019-03-14 10:47:05,729:INFO:root: Processing batch at start index 260 (num ids = 10)\n",
      "2019-03-14 10:47:11,605:INFO:root: Processing batch at start index 270 (num ids = 10)\n",
      "2019-03-14 10:47:15,506:INFO:root: Processing batch at start index 280 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:47:45,968:WARNING:root: Error occurred at index 280. Will retry up to 1000000 times\n",
      "2019-03-14 10:47:47,028:INFO:root: Processing batch at start index 280 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:48:17,295:WARNING:root: Error occurred at index 280. Will retry up to 1000000 times\n",
      "2019-03-14 10:48:18,447:INFO:root: Processing batch at start index 280 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:48:48,821:WARNING:root: Error occurred at index 280. Will retry up to 1000000 times\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-03-14 10:48:50,003:INFO:root: Processing batch at start index 280 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:49:23,951:WARNING:root: Error occurred at index 280. Will retry up to 1000000 times\n",
      "2019-03-14 10:49:25,506:INFO:root: Processing batch at start index 280 (num ids = 10)\n",
      "2019-03-14 10:49:47,010:INFO:root: Processing batch at start index 290 (num ids = 10)\n",
      "2019-03-14 10:49:50,497:INFO:root: Processing batch at start index 300 (num ids = 10)\n",
      "2019-03-14 10:49:59,223:INFO:root: Processing batch at start index 310 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:50:29,707:WARNING:root: Error occurred at index 310. Will retry up to 1000000 times\n",
      "2019-03-14 10:50:31,248:INFO:root: Processing batch at start index 310 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:51:01,529:WARNING:root: Error occurred at index 310. Will retry up to 1000000 times\n",
      "2019-03-14 10:51:03,017:INFO:root: Processing batch at start index 310 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:51:36,239:WARNING:root: Error occurred at index 310. Will retry up to 1000000 times\n",
      "2019-03-14 10:51:37,911:INFO:root: Processing batch at start index 310 (num ids = 10)\n",
      "2019-03-14 10:51:42,145:INFO:root: Processing batch at start index 320 (num ids = 10)\n",
      "2019-03-14 10:51:48,970:INFO:root: Processing batch at start index 330 (num ids = 10)\n",
      "2019-03-14 10:51:53,412:INFO:root: Processing batch at start index 340 (num ids = 10)\n",
      "2019-03-14 10:52:01,554:INFO:root: Processing batch at start index 350 (num ids = 10)\n",
      "2019-03-14 10:52:10,475:INFO:root: Processing batch at start index 360 (num ids = 10)\n",
      "2019-03-14 10:52:14,412:INFO:root: Processing batch at start index 370 (num ids = 10)\n",
      "2019-03-14 10:52:19,878:INFO:root: Processing batch at start index 380 (num ids = 10)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-03-14 10:52:22,399:INFO:root: Processing batch at start index 390 (num ids = 10)\n",
      "2019-03-14 10:52:27,307:INFO:root: Processing batch at start index 400 (num ids = 10)\n",
      "2019-03-14 10:52:30,136:INFO:root: Processing batch at start index 410 (num ids = 10)\n",
      "2019-03-14 10:52:32,703:INFO:root: Processing batch at start index 420 (num ids = 10)\n",
      "2019-03-14 10:52:40,149:INFO:root: Processing batch at start index 430 (num ids = 10)\n",
      "2019-03-14 10:52:50,718:INFO:root: Processing batch at start index 440 (num ids = 10)\n",
      "2019-03-14 10:52:53,791:INFO:root: Processing batch at start index 450 (num ids = 10)\n",
      "2019-03-14 10:53:01,470:INFO:root: Processing batch at start index 460 (num ids = 10)\n",
      "2019-03-14 10:53:03,927:INFO:root: Processing batch at start index 470 (num ids = 10)\n",
      "2019-03-14 10:53:10,993:INFO:root: Processing batch at start index 480 (num ids = 10)\n",
      "2019-03-14 10:53:13,758:INFO:root: Processing batch at start index 490 (num ids = 10)\n",
      "2019-03-14 10:53:20,822:INFO:root: Processing batch at start index 500 (num ids = 10)\n",
      "2019-03-14 10:53:24,512:INFO:root: Processing batch at start index 510 (num ids = 10)\n",
      "2019-03-14 10:53:32,497:INFO:root: Processing batch at start index 520 (num ids = 10)\n",
      "2019-03-14 10:53:36,034:INFO:root: Processing batch at start index 530 (num ids = 10)\n",
      "2019-03-14 10:53:40,791:INFO:root: Processing batch at start index 540 (num ids = 10)\n",
      "2019-03-14 10:53:44,784:INFO:root: Processing batch at start index 550 (num ids = 10)\n",
      "2019-03-14 10:53:51,771:INFO:root: Processing batch at start index 560 (num ids = 10)\n",
      "2019-03-14 10:53:55,924:INFO:root: Processing batch at start index 570 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:54:07,903:WARNING:root: Error occurred at index 570. Will retry up to 1000000 times\n",
      "2019-03-14 10:54:10,899:INFO:root: Processing batch at start index 570 (num ids = 10)\n",
      "2019-03-14 10:54:13,356:INFO:root: Processing batch at start index 580 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:54:15,704:WARNING:root: Error occurred at index 580. Will retry up to 1000000 times\n",
      "2019-03-14 10:54:32,826:INFO:root: Processing batch at start index 580 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:55:03,425:WARNING:root: Error occurred at index 580. Will retry up to 1000000 times\n",
      "2019-03-14 10:55:05,272:INFO:root: Processing batch at start index 580 (num ids = 10)\n",
      "2019-03-14 10:55:22,633:INFO:root: Processing batch at start index 590 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 55, in collect\n",
      "    ids = search(query, retstart=i, retmax=batch_size)['IdList']\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 7, in search\n",
      "    term=query)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 220, in esearch\n",
      "    return _open(cgi, variables)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:55:55,960:WARNING:root: Error occurred at index 600. Will retry up to 1000000 times\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-03-14 10:55:59,170:INFO:root: Processing batch at start index 600 (num ids = 10)\n",
      "2019-03-14 10:56:06,404:INFO:root: Processing batch at start index 610 (num ids = 10)\n",
      "2019-03-14 10:56:09,955:INFO:root: Processing batch at start index 620 (num ids = 10)\n",
      "2019-03-14 10:56:15,140:INFO:root: Processing batch at start index 630 (num ids = 10)\n",
      "2019-03-14 10:56:18,079:INFO:root: Processing batch at start index 640 (num ids = 10)\n",
      "2019-03-14 10:56:24,396:INFO:root: Processing batch at start index 650 (num ids = 10)\n",
      "2019-03-14 10:56:26,988:INFO:root: Processing batch at start index 660 (num ids = 10)\n",
      "2019-03-14 10:56:31,051:INFO:root: Processing batch at start index 670 (num ids = 10)\n",
      "2019-03-14 10:56:35,898:INFO:root: Processing batch at start index 680 (num ids = 10)\n",
      "2019-03-14 10:56:39,496:INFO:root: Processing batch at start index 690 (num ids = 10)\n",
      "2019-03-14 10:56:45,905:INFO:root: Processing batch at start index 700 (num ids = 10)\n",
      "2019-03-14 10:56:49,668:INFO:root: Processing batch at start index 710 (num ids = 10)\n",
      "2019-03-14 10:56:57,490:INFO:root: Processing batch at start index 720 (num ids = 10)\n",
      "2019-03-14 10:57:03,169:INFO:root: Processing batch at start index 730 (num ids = 10)\n",
      "2019-03-14 10:57:07,913:INFO:root: Processing batch at start index 740 (num ids = 10)\n",
      "2019-03-14 10:57:10,667:INFO:root: Processing batch at start index 750 (num ids = 10)\n",
      "2019-03-14 10:57:16,610:INFO:root: Processing batch at start index 760 (num ids = 10)\n",
      "2019-03-14 10:57:20,335:INFO:root: Processing batch at start index 770 (num ids = 10)\n",
      "2019-03-14 10:57:37,861:INFO:root: Processing batch at start index 780 (num ids = 10)\n",
      "2019-03-14 10:58:03,708:INFO:root: Processing batch at start index 790 (num ids = 10)\n",
      "2019-03-14 10:58:07,753:INFO:root: Processing batch at start index 800 (num ids = 10)\n",
      "2019-03-14 10:58:10,153:INFO:root: Processing batch at start index 810 (num ids = 10)\n",
      "2019-03-14 10:58:17,892:INFO:root: Processing batch at start index 820 (num ids = 10)\n",
      "2019-03-14 10:58:20,634:INFO:root: Processing batch at start index 830 (num ids = 10)\n",
      "2019-03-14 10:58:27,554:INFO:root: Processing batch at start index 840 (num ids = 10)\n",
      "2019-03-14 10:58:30,106:INFO:root: Processing batch at start index 850 (num ids = 10)\n",
      "2019-03-14 10:58:36,070:INFO:root: Processing batch at start index 860 (num ids = 10)\n",
      "2019-03-14 10:58:40,446:INFO:root: Processing batch at start index 870 (num ids = 10)\n",
      "2019-03-14 10:58:46,516:INFO:root: Processing batch at start index 880 (num ids = 10)\n",
      "2019-03-14 10:58:49,530:INFO:root: Processing batch at start index 890 (num ids = 10)\n",
      "2019-03-14 10:58:52,268:INFO:root: Processing batch at start index 900 (num ids = 10)\n",
      "2019-03-14 10:59:01,758:INFO:root: Processing batch at start index 910 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:59:05,013:WARNING:root: Error occurred at index 910. Will retry up to 1000000 times\n",
      "2019-03-14 10:59:10,072:INFO:root: Processing batch at start index 910 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 500: Internal Server Error\n",
      "2019-03-14 10:59:10,426:WARNING:root: Error occurred at index 910. Will retry up to 1000000 times\n",
      "2019-03-14 10:59:11,546:INFO:root: Processing batch at start index 910 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 55, in collect\n",
      "    ids = search(query, retstart=i, retmax=batch_size)['IdList']\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 7, in search\n",
      "    term=query)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 220, in esearch\n",
      "    return _open(cgi, variables)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 10:59:19,325:WARNING:root: Error occurred at index 920. Will retry up to 1000000 times\n",
      "2019-03-14 10:59:21,429:INFO:root: Processing batch at start index 920 (num ids = 10)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-03-14 10:59:27,684:INFO:root: Processing batch at start index 930 (num ids = 10)\n",
      "2019-03-14 10:59:30,082:INFO:root: Processing batch at start index 940 (num ids = 10)\n",
      "2019-03-14 10:59:34,266:INFO:root: Processing batch at start index 950 (num ids = 10)\n",
      "2019-03-14 10:59:38,991:INFO:root: Processing batch at start index 960 (num ids = 10)\n",
      "2019-03-14 10:59:41,958:INFO:root: Processing batch at start index 970 (num ids = 10)\n",
      "2019-03-14 10:59:49,131:INFO:root: Processing batch at start index 980 (num ids = 10)\n",
      "2019-03-14 10:59:51,888:INFO:root: Processing batch at start index 990 (num ids = 10)\n",
      "2019-03-14 10:59:59,507:INFO:root: Processing batch at start index 1000 (num ids = 10)\n",
      "2019-03-14 11:00:03,825:INFO:root: Processing batch at start index 1010 (num ids = 10)\n",
      "2019-03-14 11:00:10,324:INFO:root: Processing batch at start index 1020 (num ids = 10)\n",
      "2019-03-14 11:00:12,877:INFO:root: Processing batch at start index 1030 (num ids = 10)\n",
      "2019-03-14 11:00:19,932:INFO:root: Processing batch at start index 1040 (num ids = 10)\n",
      "2019-03-14 11:00:22,699:INFO:root: Processing batch at start index 1050 (num ids = 10)\n",
      "2019-03-14 11:00:37,800:INFO:root: Processing batch at start index 1060 (num ids = 10)\n",
      "2019-03-14 11:00:40,636:INFO:root: Processing batch at start index 1070 (num ids = 10)\n",
      "2019-03-14 11:00:59,476:INFO:root: Processing batch at start index 1080 (num ids = 10)\n",
      "2019-03-14 11:01:03,690:INFO:root: Processing batch at start index 1090 (num ids = 10)\n",
      "2019-03-14 11:01:08,460:INFO:root: Processing batch at start index 1100 (num ids = 10)\n",
      "2019-03-14 11:01:12,690:INFO:root: Processing batch at start index 1110 (num ids = 10)\n",
      "2019-03-14 11:01:15,378:INFO:root: Processing batch at start index 1120 (num ids = 10)\n",
      "2019-03-14 11:01:22,519:INFO:root: Processing batch at start index 1130 (num ids = 10)\n",
      "2019-03-14 11:01:29,953:INFO:root: Processing batch at start index 1140 (num ids = 10)\n",
      "2019-03-14 11:01:34,055:INFO:root: Processing batch at start index 1150 (num ids = 10)\n",
      "2019-03-14 11:01:40,321:INFO:root: Processing batch at start index 1160 (num ids = 10)\n",
      "2019-03-14 11:01:42,971:INFO:root: Processing batch at start index 1170 (num ids = 10)\n",
      "2019-03-14 11:01:45,893:INFO:root: Processing batch at start index 1180 (num ids = 10)\n",
      "2019-03-14 11:01:51,396:INFO:root: Processing batch at start index 1190 (num ids = 10)\n",
      "2019-03-14 11:01:54,187:INFO:root: Processing batch at start index 1200 (num ids = 10)\n",
      "2019-03-14 11:01:59,418:INFO:root: Processing batch at start index 1210 (num ids = 10)\n",
      "2019-03-14 11:02:02,350:INFO:root: Processing batch at start index 1220 (num ids = 10)\n",
      "2019-03-14 11:02:06,348:INFO:root: Processing batch at start index 1230 (num ids = 10)\n",
      "2019-03-14 11:02:12,883:INFO:root: Processing batch at start index 1240 (num ids = 10)\n",
      "2019-03-14 11:02:15,853:INFO:root: Processing batch at start index 1250 (num ids = 10)\n",
      "2019-03-14 11:02:22,731:INFO:root: Processing batch at start index 1260 (num ids = 10)\n",
      "2019-03-14 11:02:25,804:INFO:root: Processing batch at start index 1270 (num ids = 10)\n",
      "2019-03-14 11:02:33,174:INFO:root: Processing batch at start index 1280 (num ids = 10)\n",
      "2019-03-14 11:02:35,943:INFO:root: Processing batch at start index 1290 (num ids = 10)\n",
      "2019-03-14 11:02:42,100:INFO:root: Processing batch at start index 1300 (num ids = 10)\n",
      "2019-03-14 11:02:44,848:INFO:root: Processing batch at start index 1310 (num ids = 10)\n",
      "2019-03-14 11:02:51,518:INFO:root: Processing batch at start index 1320 (num ids = 10)\n",
      "2019-03-14 11:02:54,371:INFO:root: Processing batch at start index 1330 (num ids = 10)\n",
      "2019-03-14 11:03:01,802:INFO:root: Processing batch at start index 1340 (num ids = 10)\n",
      "2019-03-14 11:03:04,643:INFO:root: Processing batch at start index 1350 (num ids = 10)\n",
      "2019-03-14 11:03:06,936:INFO:root: Processing batch at start index 1360 (num ids = 10)\n",
      "2019-03-14 11:03:15,962:INFO:root: Processing batch at start index 1370 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 11:03:17,952:WARNING:root: Error occurred at index 1370. Will retry up to 1000000 times\n",
      "2019-03-14 11:03:22,632:INFO:root: Processing batch at start index 1370 (num ids = 10)\n",
      "2019-03-14 11:03:24,878:INFO:root: Processing batch at start index 1380 (num ids = 10)\n",
      "2019-03-14 11:03:27,547:INFO:root: Processing batch at start index 1390 (num ids = 10)\n",
      "2019-03-14 11:03:35,846:INFO:root: Processing batch at start index 1400 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 55, in collect\n",
      "    ids = search(query, retstart=i, retmax=batch_size)['IdList']\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 7, in search\n",
      "    term=query)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 220, in esearch\n",
      "    return _open(cgi, variables)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 11:03:40,105:WARNING:root: Error occurred at index 1410. Will retry up to 1000000 times\n",
      "2019-03-14 11:03:43,100:INFO:root: Processing batch at start index 1410 (num ids = 10)\n",
      "2019-03-14 11:03:45,985:INFO:root: Processing batch at start index 1420 (num ids = 10)\n",
      "2019-03-14 11:03:52,799:INFO:root: Processing batch at start index 1430 (num ids = 10)\n",
      "2019-03-14 11:03:55,814:INFO:root: Processing batch at start index 1440 (num ids = 10)\n",
      "2019-03-14 11:03:58,787:INFO:root: Processing batch at start index 1450 (num ids = 10)\n",
      "2019-03-14 11:04:05,335:INFO:root: Processing batch at start index 1460 (num ids = 10)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-03-14 11:04:13,630:INFO:root: Processing batch at start index 1470 (num ids = 10)\n",
      "2019-03-14 11:04:17,250:INFO:root: Processing batch at start index 1480 (num ids = 10)\n",
      "2019-03-14 11:04:21,741:INFO:root: Processing batch at start index 1490 (num ids = 10)\n",
      "2019-03-14 11:04:24,999:INFO:root: Processing batch at start index 1500 (num ids = 10)\n",
      "2019-03-14 11:04:28,388:INFO:root: Processing batch at start index 1510 (num ids = 10)\n",
      "2019-03-14 11:04:34,694:INFO:root: Processing batch at start index 1520 (num ids = 10)\n",
      "2019-03-14 11:04:38,329:INFO:root: Processing batch at start index 1530 (num ids = 10)\n",
      "2019-03-14 11:04:45,708:INFO:root: Processing batch at start index 1540 (num ids = 10)\n",
      "2019-03-14 11:04:48,960:INFO:root: Processing batch at start index 1550 (num ids = 10)\n",
      "2019-03-14 11:04:56,329:INFO:root: Processing batch at start index 1560 (num ids = 10)\n",
      "2019-03-14 11:04:59,401:INFO:root: Processing batch at start index 1570 (num ids = 10)\n",
      "2019-03-14 11:05:05,545:INFO:root: Processing batch at start index 1580 (num ids = 10)\n",
      "2019-03-14 11:05:07,992:INFO:root: Processing batch at start index 1590 (num ids = 10)\n",
      "2019-03-14 11:05:14,513:INFO:root: Processing batch at start index 1600 (num ids = 10)\n",
      "2019-03-14 11:05:16,992:INFO:root: Processing batch at start index 1610 (num ids = 10)\n",
      "2019-03-14 11:05:19,646:INFO:root: Processing batch at start index 1620 (num ids = 10)\n",
      "2019-03-14 11:05:26,744:INFO:root: Processing batch at start index 1630 (num ids = 10)\n",
      "2019-03-14 11:05:29,218:INFO:root: Processing batch at start index 1640 (num ids = 10)\n",
      "2019-03-14 11:05:36,265:INFO:root: Processing batch at start index 1650 (num ids = 10)\n",
      "2019-03-14 11:05:39,342:INFO:root: Processing batch at start index 1660 (num ids = 10)\n",
      "2019-03-14 11:05:47,942:INFO:root: Processing batch at start index 1670 (num ids = 10)\n",
      "2019-03-14 11:05:51,114:INFO:root: Processing batch at start index 1680 (num ids = 10)\n",
      "2019-03-14 11:05:58,122:INFO:root: Processing batch at start index 1690 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 55, in collect\n",
      "    ids = search(query, retstart=i, retmax=batch_size)['IdList']\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 7, in search\n",
      "    term=query)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 220, in esearch\n",
      "    return _open(cgi, variables)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 11:06:12,048:WARNING:root: Error occurred at index 1700. Will retry up to 1000000 times\n",
      "2019-03-14 11:06:15,894:INFO:root: Processing batch at start index 1700 (num ids = 10)\n",
      "2019-03-14 11:06:18,174:INFO:root: Processing batch at start index 1710 (num ids = 10)\n",
      "2019-03-14 11:06:21,667:INFO:root: Processing batch at start index 1720 (num ids = 10)\n",
      "2019-03-14 11:06:28,488:INFO:root: Processing batch at start index 1730 (num ids = 10)\n",
      "2019-03-14 11:06:31,254:INFO:root: Processing batch at start index 1740 (num ids = 10)\n",
      "2019-03-14 11:06:37,769:INFO:root: Processing batch at start index 1750 (num ids = 10)\n",
      "2019-03-14 11:06:40,778:INFO:root: Processing batch at start index 1760 (num ids = 10)\n",
      "2019-03-14 11:06:47,845:INFO:root: Processing batch at start index 1770 (num ids = 10)\n",
      "2019-03-14 11:06:50,507:INFO:root: Processing batch at start index 1780 (num ids = 10)\n",
      "2019-03-14 11:06:58,114:INFO:root: Processing batch at start index 1790 (num ids = 10)\n",
      "2019-03-14 11:07:01,088:INFO:root: Processing batch at start index 1800 (num ids = 10)\n",
      "2019-03-14 11:07:07,228:INFO:root: Processing batch at start index 1810 (num ids = 10)\n",
      "2019-03-14 11:07:11,498:INFO:root: Processing batch at start index 1820 (num ids = 10)\n",
      "2019-03-14 11:07:18,143:INFO:root: Processing batch at start index 1830 (num ids = 10)\n",
      "2019-03-14 11:07:20,719:INFO:root: Processing batch at start index 1840 (num ids = 10)\n",
      "2019-03-14 11:07:27,224:INFO:root: Processing batch at start index 1850 (num ids = 10)\n",
      "2019-03-14 11:07:30,545:INFO:root: Processing batch at start index 1860 (num ids = 10)\n",
      "2019-03-14 11:07:37,099:INFO:root: Processing batch at start index 1870 (num ids = 10)\n",
      "2019-03-14 11:07:39,337:INFO:root: Processing batch at start index 1880 (num ids = 10)\n",
      "2019-03-14 11:07:41,760:INFO:root: Processing batch at start index 1890 (num ids = 10)\n",
      "2019-03-14 11:07:48,978:INFO:root: Processing batch at start index 1900 (num ids = 10)\n",
      "2019-03-14 11:07:51,613:INFO:root: Processing batch at start index 1910 (num ids = 10)\n",
      "2019-03-14 11:07:57,710:INFO:root: Processing batch at start index 1920 (num ids = 10)\n",
      "2019-03-14 11:08:02,493:INFO:root: Processing batch at start index 1930 (num ids = 10)\n",
      "2019-03-14 11:08:09,251:INFO:root: Processing batch at start index 1940 (num ids = 10)\n",
      "2019-03-14 11:08:11,708:INFO:root: Processing batch at start index 1950 (num ids = 10)\n",
      "2019-03-14 11:08:17,911:INFO:root: Processing batch at start index 1960 (num ids = 10)\n",
      "2019-03-14 11:08:20,949:INFO:root: Processing batch at start index 1970 (num ids = 10)\n",
      "2019-03-14 11:08:24,959:INFO:root: Processing batch at start index 1980 (num ids = 10)\n",
      "2019-03-14 11:08:31,063:INFO:root: Processing batch at start index 1990 (num ids = 10)\n",
      "2019-03-14 11:08:34,066:INFO:root: Processing batch at start index 2000 (num ids = 10)\n",
      "2019-03-14 11:08:40,291:INFO:root: Processing batch at start index 2010 (num ids = 10)\n",
      "2019-03-14 11:08:42,804:INFO:root: Processing batch at start index 2020 (num ids = 10)\n",
      "2019-03-14 11:08:49,834:INFO:root: Processing batch at start index 2030 (num ids = 10)\n",
      "2019-03-14 11:09:00,359:INFO:root: Processing batch at start index 2040 (num ids = 10)\n",
      "2019-03-14 11:09:03,921:INFO:root: Processing batch at start index 2050 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 55, in collect\n",
      "    ids = search(query, retstart=i, retmax=batch_size)['IdList']\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 7, in search\n",
      "    term=query)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 220, in esearch\n",
      "    return _open(cgi, variables)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 11:09:12,791:WARNING:root: Error occurred at index 2060. Will retry up to 1000000 times\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-03-14 11:09:14,073:INFO:root: Processing batch at start index 2060 (num ids = 10)\n",
      "2019-03-14 11:09:21,445:INFO:root: Processing batch at start index 2070 (num ids = 10)\n",
      "2019-03-14 11:09:29,798:INFO:root: Processing batch at start index 2080 (num ids = 10)\n",
      "2019-03-14 11:09:31,822:INFO:root: Processing batch at start index 2090 (num ids = 10)\n",
      "2019-03-14 11:09:34,348:INFO:root: Processing batch at start index 2100 (num ids = 10)\n",
      "2019-03-14 11:09:41,413:INFO:root: Processing batch at start index 2110 (num ids = 10)\n",
      "2019-03-14 11:09:44,483:INFO:root: Processing batch at start index 2120 (num ids = 10)\n",
      "2019-03-14 11:09:51,714:INFO:root: Processing batch at start index 2130 (num ids = 10)\n",
      "2019-03-14 11:09:54,269:INFO:root: Processing batch at start index 2140 (num ids = 10)\n",
      "2019-03-14 11:10:01,073:INFO:root: Processing batch at start index 2150 (num ids = 10)\n",
      "2019-03-14 11:10:04,235:INFO:root: Processing batch at start index 2160 (num ids = 10)\n",
      "2019-03-14 11:10:14,620:INFO:root: Processing batch at start index 2170 (num ids = 10)\n",
      "2019-03-14 11:10:21,937:INFO:root: Processing batch at start index 2180 (num ids = 10)\n",
      "2019-03-14 11:10:25,344:INFO:root: Processing batch at start index 2190 (num ids = 10)\n",
      "2019-03-14 11:10:32,128:INFO:root: Processing batch at start index 2200 (num ids = 10)\n",
      "2019-03-14 11:10:35,482:INFO:root: Processing batch at start index 2210 (num ids = 10)\n",
      "2019-03-14 11:10:42,244:INFO:root: Processing batch at start index 2220 (num ids = 10)\n",
      "2019-03-14 11:10:44,982:INFO:root: Processing batch at start index 2230 (num ids = 10)\n",
      "2019-03-14 11:10:51,278:INFO:root: Processing batch at start index 2240 (num ids = 10)\n",
      "2019-03-14 11:10:53,467:INFO:root: Processing batch at start index 2250 (num ids = 10)\n",
      "2019-03-14 11:10:56,973:INFO:root: Processing batch at start index 2260 (num ids = 10)\n",
      "2019-03-14 11:11:03,115:INFO:root: Processing batch at start index 2270 (num ids = 10)\n",
      "2019-03-14 11:11:05,540:INFO:root: Processing batch at start index 2280 (num ids = 10)\n",
      "2019-03-14 11:11:13,290:INFO:root: Processing batch at start index 2290 (num ids = 10)\n",
      "2019-03-14 11:11:15,571:INFO:root: Processing batch at start index 2300 (num ids = 10)\n",
      "2019-03-14 11:11:21,616:INFO:root: Processing batch at start index 2310 (num ids = 10)\n",
      "2019-03-14 11:11:24,941:INFO:root: Processing batch at start index 2320 (num ids = 10)\n",
      "2019-03-14 11:11:31,998:INFO:root: Processing batch at start index 2330 (num ids = 10)\n",
      "2019-03-14 11:11:35,387:INFO:root: Processing batch at start index 2340 (num ids = 10)\n",
      "2019-03-14 11:11:39,628:INFO:root: Processing batch at start index 2350 (num ids = 10)\n",
      "2019-03-14 11:11:43,878:INFO:root: Processing batch at start index 2360 (num ids = 10)\n",
      "2019-03-14 11:11:46,731:INFO:root: Processing batch at start index 2370 (num ids = 10)\n",
      "2019-03-14 11:11:54,378:INFO:root: Processing batch at start index 2380 (num ids = 10)\n",
      "2019-03-14 11:11:57,196:INFO:root: Processing batch at start index 2390 (num ids = 10)\n",
      "2019-03-14 11:12:04,570:INFO:root: Processing batch at start index 2400 (num ids = 10)\n",
      "2019-03-14 11:12:08,351:INFO:root: Processing batch at start index 2410 (num ids = 10)\n",
      "2019-03-14 11:12:14,705:INFO:root: Processing batch at start index 2420 (num ids = 10)\n",
      "2019-03-14 11:12:17,781:INFO:root: Processing batch at start index 2430 (num ids = 10)\n",
      "2019-03-14 11:12:24,248:INFO:root: Processing batch at start index 2440 (num ids = 10)\n",
      "2019-03-14 11:12:27,059:INFO:root: Processing batch at start index 2450 (num ids = 10)\n",
      "2019-03-14 11:12:33,443:INFO:root: Processing batch at start index 2460 (num ids = 10)\n",
      "2019-03-14 11:12:36,392:INFO:root: Processing batch at start index 2470 (num ids = 10)\n",
      "2019-03-14 11:12:40,684:INFO:root: Processing batch at start index 2480 (num ids = 10)\n",
      "2019-03-14 11:12:45,427:INFO:root: Processing batch at start index 2490 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 55, in collect\n",
      "    ids = search(query, retstart=i, retmax=batch_size)['IdList']\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 7, in search\n",
      "    term=query)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 220, in esearch\n",
      "    return _open(cgi, variables)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 11:12:54,332:WARNING:root: Error occurred at index 2500. Will retry up to 1000000 times\n",
      "2019-03-14 11:13:16,961:INFO:root: Processing batch at start index 2500 (num ids = 10)\n",
      "2019-03-14 11:13:19,638:INFO:root: Processing batch at start index 2510 (num ids = 10)\n",
      "2019-03-14 11:13:26,435:INFO:root: Processing batch at start index 2520 (num ids = 10)\n",
      "2019-03-14 11:13:29,094:INFO:root: Processing batch at start index 2530 (num ids = 10)\n",
      "2019-03-14 11:13:35,815:INFO:root: Processing batch at start index 2540 (num ids = 10)\n",
      "2019-03-14 11:13:39,481:INFO:root: Processing batch at start index 2550 (num ids = 10)\n",
      "2019-03-14 11:13:47,480:INFO:root: Processing batch at start index 2560 (num ids = 10)\n",
      "2019-03-14 11:13:50,882:INFO:root: Processing batch at start index 2570 (num ids = 10)\n",
      "2019-03-14 11:13:56,697:INFO:root: Processing batch at start index 2580 (num ids = 10)\n",
      "2019-03-14 11:14:17,248:INFO:root: Processing batch at start index 2590 (num ids = 10)\n",
      "2019-03-14 11:14:19,676:INFO:root: Processing batch at start index 2600 (num ids = 10)\n",
      "2019-03-14 11:14:27,992:INFO:root: Processing batch at start index 2610 (num ids = 10)\n",
      "2019-03-14 11:14:33,611:INFO:root: Processing batch at start index 2620 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 1318, in do_open\n",
      "    encode_chunked=req.has_header('Transfer-encoding'))\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1400, in connect\n",
      "    server_hostname=server_hostname)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 407, in wrap_socket\n",
      "    _context=self, _session=session)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 817, in __init__\n",
      "    self.do_handshake()\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 1077, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 689, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "ConnectionResetError: [Errno 54] Connection reset by peer\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 526, in open\n",
      "    response = self._open(req, data)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 544, in _open\n",
      "    '_open', req)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 1361, in https_open\n",
      "    context=self._context, check_hostname=self._check_hostname)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 1320, in do_open\n",
      "    raise URLError(err)\n",
      "urllib.error.URLError: <urlopen error [Errno 54] Connection reset by peer>\n",
      "2019-03-14 11:14:34,711:WARNING:root: Error occurred at index 2620. Will retry up to 1000000 times\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-03-14 11:14:36,020:INFO:root: Processing batch at start index 2620 (num ids = 10)\n",
      "2019-03-14 11:14:38,784:INFO:root: Processing batch at start index 2630 (num ids = 10)\n",
      "2019-03-14 11:14:41,222:INFO:root: Processing batch at start index 2640 (num ids = 10)\n",
      "2019-03-14 11:14:48,004:INFO:root: Processing batch at start index 2650 (num ids = 10)\n",
      "2019-03-14 11:14:50,289:INFO:root: Processing batch at start index 2660 (num ids = 10)\n",
      "2019-03-14 11:14:57,823:INFO:root: Processing batch at start index 2670 (num ids = 10)\n",
      "2019-03-14 11:15:01,569:INFO:root: Processing batch at start index 2680 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 1318, in do_open\n",
      "    encode_chunked=req.has_header('Transfer-encoding'))\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1400, in connect\n",
      "    server_hostname=server_hostname)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 407, in wrap_socket\n",
      "    _context=self, _session=session)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 817, in __init__\n",
      "    self.do_handshake()\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 1077, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 689, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "ConnectionResetError: [Errno 54] Connection reset by peer\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 526, in open\n",
      "    response = self._open(req, data)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 544, in _open\n",
      "    '_open', req)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 1361, in https_open\n",
      "    context=self._context, check_hostname=self._check_hostname)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 1320, in do_open\n",
      "    raise URLError(err)\n",
      "urllib.error.URLError: <urlopen error [Errno 54] Connection reset by peer>\n",
      "2019-03-14 11:15:03,304:WARNING:root: Error occurred at index 2680. Will retry up to 1000000 times\n",
      "2019-03-14 11:15:06,247:INFO:root: Processing batch at start index 2680 (num ids = 10)\n",
      "2019-03-14 11:15:09,562:INFO:root: Processing batch at start index 2690 (num ids = 10)\n",
      "2019-03-14 11:15:14,989:INFO:root: Processing batch at start index 2700 (num ids = 10)\n",
      "2019-03-14 11:15:17,492:INFO:root: Processing batch at start index 2710 (num ids = 10)\n",
      "2019-03-14 11:15:21,133:INFO:root: Processing batch at start index 2720 (num ids = 10)\n",
      "2019-03-14 11:15:28,245:INFO:root: Processing batch at start index 2730 (num ids = 10)\n",
      "2019-03-14 11:15:30,941:INFO:root: Processing batch at start index 2740 (num ids = 10)\n",
      "2019-03-14 11:15:37,390:INFO:root: Processing batch at start index 2750 (num ids = 10)\n",
      "2019-03-14 11:15:39,782:INFO:root: Processing batch at start index 2760 (num ids = 10)\n",
      "2019-03-14 11:15:44,690:INFO:root: Processing batch at start index 2770 (num ids = 10)\n",
      "2019-03-14 11:15:49,440:INFO:root: Processing batch at start index 2780 (num ids = 10)\n",
      "2019-03-14 11:15:56,564:INFO:root: Processing batch at start index 2790 (num ids = 10)\n",
      "2019-03-14 11:15:58,965:INFO:root: Processing batch at start index 2800 (num ids = 10)\n",
      "2019-03-14 11:16:01,727:INFO:root: Processing batch at start index 2810 (num ids = 10)\n",
      "2019-03-14 11:16:07,565:INFO:root: Processing batch at start index 2820 (num ids = 10)\n",
      "2019-03-14 11:16:10,945:INFO:root: Processing batch at start index 2830 (num ids = 10)\n",
      "2019-03-14 11:16:18,010:INFO:root: Processing batch at start index 2840 (num ids = 10)\n",
      "2019-03-14 11:16:20,469:INFO:root: Processing batch at start index 2850 (num ids = 10)\n",
      "2019-03-14 11:16:25,283:INFO:root: Processing batch at start index 2860 (num ids = 10)\n",
      "2019-03-14 11:16:29,036:INFO:root: Processing batch at start index 2870 (num ids = 10)\n",
      "2019-03-14 11:16:31,555:INFO:root: Processing batch at start index 2880 (num ids = 10)\n",
      "2019-03-14 11:16:39,207:INFO:root: Processing batch at start index 2890 (num ids = 10)\n",
      "2019-03-14 11:16:47,254:INFO:root: Processing batch at start index 2900 (num ids = 10)\n",
      "2019-03-14 11:16:51,699:INFO:root: Processing batch at start index 2910 (num ids = 10)\n",
      "2019-03-14 11:16:58,563:INFO:root: Processing batch at start index 2920 (num ids = 10)\n",
      "2019-03-14 11:17:01,098:INFO:root: Processing batch at start index 2930 (num ids = 10)\n",
      "2019-03-14 11:17:03,935:INFO:root: Processing batch at start index 2940 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 545, in _open\n",
      "    raise exception\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 532, in open\n",
      "    response = meth(req, response)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 642, in http_response\n",
      "    'http', request, response, code, msg, hdrs)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 570, in error\n",
      "    return self._call_chain(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 650, in http_error_default\n",
      "    raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "urllib.error.HTTPError: HTTP Error 502: Bad Gateway\n",
      "2019-03-14 11:17:10,231:WARNING:root: Error occurred at index 2940. Will retry up to 1000000 times\n",
      "2019-03-14 11:17:11,772:INFO:root: Processing batch at start index 2940 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 1318, in do_open\n",
      "    encode_chunked=req.has_header('Transfer-encoding'))\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1400, in connect\n",
      "    server_hostname=server_hostname)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 407, in wrap_socket\n",
      "    _context=self, _session=session)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 817, in __init__\n",
      "    self.do_handshake()\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 1077, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 689, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "ConnectionResetError: [Errno 54] Connection reset by peer\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 55, in collect\n",
      "    ids = search(query, retstart=i, retmax=batch_size)['IdList']\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 7, in search\n",
      "    term=query)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 220, in esearch\n",
      "    return _open(cgi, variables)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 526, in open\n",
      "    response = self._open(req, data)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 544, in _open\n",
      "    '_open', req)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 1361, in https_open\n",
      "    context=self._context, check_hostname=self._check_hostname)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 1320, in do_open\n",
      "    raise URLError(err)\n",
      "urllib.error.URLError: <urlopen error [Errno 54] Connection reset by peer>\n",
      "2019-03-14 11:17:17,039:WARNING:root: Error occurred at index 2950. Will retry up to 1000000 times\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2019-03-14 11:17:18,099:INFO:root: Processing batch at start index 2950 (num ids = 10)\n",
      "2019-03-14 11:17:23,700:INFO:root: Processing batch at start index 2960 (num ids = 10)\n",
      "2019-03-14 11:17:29,895:INFO:root: Processing batch at start index 2970 (num ids = 10)\n",
      "2019-03-14 11:17:32,545:INFO:root: Processing batch at start index 2980 (num ids = 10)\n",
      "2019-03-14 11:17:38,498:INFO:root: Processing batch at start index 2990 (num ids = 10)\n",
      "2019-03-14 11:17:41,228:INFO:root: Processing batch at start index 3000 (num ids = 10)\n",
      "2019-03-14 11:17:48,389:INFO:root: Processing batch at start index 3010 (num ids = 10)\n",
      "2019-03-14 11:17:51,558:INFO:root: Processing batch at start index 3020 (num ids = 10)\n",
      "2019-03-14 11:17:54,797:INFO:root: Processing batch at start index 3030 (num ids = 10)\n",
      "2019-03-14 11:18:00,922:INFO:root: Processing batch at start index 3040 (num ids = 10)\n",
      "2019-03-14 11:18:03,383:INFO:root: Processing batch at start index 3050 (num ids = 10)\n",
      "2019-03-14 11:18:10,755:INFO:root: Processing batch at start index 3060 (num ids = 10)\n",
      "2019-03-14 11:18:13,312:INFO:root: Processing batch at start index 3070 (num ids = 10)\n",
      "2019-03-14 11:18:21,505:INFO:root: Processing batch at start index 3080 (num ids = 10)\n",
      "2019-03-14 11:18:24,825:INFO:root: Processing batch at start index 3090 (num ids = 10)\n",
      "2019-03-14 11:18:31,336:INFO:root: Processing batch at start index 3100 (num ids = 10)\n",
      "2019-03-14 11:18:34,101:INFO:root: Processing batch at start index 3110 (num ids = 10)\n",
      "2019-03-14 11:18:41,473:INFO:root: Processing batch at start index 3120 (num ids = 10)\n",
      "2019-03-14 11:18:44,020:INFO:root: Processing batch at start index 3130 (num ids = 10)\n",
      "2019-03-14 11:18:50,520:INFO:root: Processing batch at start index 3140 (num ids = 10)\n",
      "2019-03-14 11:18:52,806:INFO:root: Processing batch at start index 3150 (num ids = 10)\n",
      "2019-03-14 11:18:57,221:INFO:root: Processing batch at start index 3160 (num ids = 10)\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 1318, in do_open\n",
      "    encode_chunked=req.has_header('Transfer-encoding'))\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1239, in request\n",
      "    self._send_request(method, url, body, headers, encode_chunked)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1285, in _send_request\n",
      "    self.endheaders(body, encode_chunked=encode_chunked)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1234, in endheaders\n",
      "    self._send_output(message_body, encode_chunked=encode_chunked)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1026, in _send_output\n",
      "    self.send(msg)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 964, in send\n",
      "    self.connect()\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/http/client.py\", line 1400, in connect\n",
      "    server_hostname=server_hostname)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 407, in wrap_socket\n",
      "    _context=self, _session=session)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 817, in __init__\n",
      "    self.do_handshake()\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 1077, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/ssl.py\", line 689, in do_handshake\n",
      "    self._sslobj.do_handshake()\n",
      "ConnectionResetError: [Errno 54] Connection reset by peer\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 59, in collect\n",
      "    dets = fetch_details(ids)\n",
      "  File \"<ipython-input-3-6c5b1272821b>\", line 13, in fetch_details\n",
      "    handle = Entrez.efetch(db='pmc', rettype=\"full\", retmode='xml', id=ids)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 184, in efetch\n",
      "    return _open(cgi, variables, post=post)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/site-packages/Bio/Entrez/__init__.py\", line 543, in _open\n",
      "    handle = _urlopen(cgi)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 223, in urlopen\n",
      "    return opener.open(url, data, timeout)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 526, in open\n",
      "    response = self._open(req, data)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 544, in _open\n",
      "    '_open', req)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 504, in _call_chain\n",
      "    result = func(*args)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 1361, in https_open\n",
      "    context=self._context, check_hostname=self._check_hostname)\n",
      "  File \"/Users/eczech/anaconda3/envs/pubmed-nlp/lib/python3.6/urllib/request.py\", line 1320, in do_open\n",
      "    raise URLError(err)\n",
      "urllib.error.URLError: <urlopen error [Errno 54] Connection reset by peer>\n",
      "2019-03-14 11:18:59,022:WARNING:root: Error occurred at index 3160. Will retry up to 1000000 times\n",
      "2019-03-14 11:19:00,212:INFO:root: Processing batch at start index 3160 (num ids = 10)\n",
      "2019-03-14 11:19:02,338:INFO:root: Processing batch at start index 3170 (num ids = 10)\n",
      "2019-03-14 11:19:04,820:INFO:root: Processing batch at start index 3180 (num ids = 10)\n",
      "2019-03-14 11:19:11,324:INFO:root: Processing batch at start index 3190 (num ids = 10)\n",
      "2019-03-14 11:19:14,212:INFO:root: Processing batch at start index 3200 (num ids = 10)\n",
      "2019-03-14 11:19:21,103:INFO:root: Processing batch at start index 3210 (num ids = 10)\n",
      "2019-03-14 11:19:23,560:INFO:root: Processing batch at start index 3220 (num ids = 10)\n",
      "2019-03-14 11:19:28,627:INFO:root: Processing batch at start index 3230 (num ids = 10)\n",
      "2019-03-14 11:19:31,548:INFO:root: Processing batch at start index 3240 (num ids = 10)\n",
      "2019-03-14 11:19:34,625:INFO:root: Processing batch at start index 3250 (num ids = 10)\n",
      "2019-03-14 11:19:41,921:INFO:root: Processing batch at start index 3260 (num ids = 10)\n",
      "2019-03-14 11:19:44,145:INFO:root: Processing batch at start index 3270 (num ids = 10)\n",
      "2019-03-14 11:19:47,104:INFO:root: Processing batch at start index 3280 (num ids = 10)\n",
      "2019-03-14 11:19:52,335:INFO:root: Processing batch at start index 3290 (num ids = 10)\n",
      "2019-03-14 11:19:55,136:INFO:root: Processing batch at start index 3300 (num ids = 10)\n",
      "2019-03-14 11:20:02,881:INFO:root: Processing batch at start index 3310 (num ids = 10)\n",
      "2019-03-14 11:20:05,094:INFO:root: Processing batch at start index 3320 (num ids = 10)\n",
      "2019-03-14 11:20:14,248:INFO:root: Processing batch at start index 3330 (num ids = 10)\n",
      "2019-03-14 11:20:17,634:INFO:root: Processing batch at start index 3340 (num ids = 10)\n",
      "2019-03-14 11:20:24,386:INFO:root: Processing batch at start index 3350 (num ids = 10)\n",
      "2019-03-14 11:20:27,868:INFO:root: Processing batch at start index 3360 (num ids = 10)\n",
      "2019-03-14 11:20:33,700:INFO:root: Processing batch at start index 3370 (num ids = 10)\n",
      "2019-03-14 11:20:37,528:INFO:root: Processing batch at start index 3380 (num ids = 10)\n",
      "2019-03-14 11:20:43,774:INFO:root: Processing batch at start index 3390 (num ids = 10)\n",
      "2019-03-14 11:20:46,435:INFO:root: Processing batch at start index 3400 (num ids = 10)\n",
      "2019-03-14 11:20:53,570:INFO:root: Processing batch at start index 3410 (num ids = 10)\n",
      "2019-03-14 11:20:55,761:INFO:root: Processing batch at start index 3420 (num ids = 10)\n",
      "2019-03-14 11:21:02,132:INFO:root: Processing batch at start index 3430 (num ids = 10)\n",
      "2019-03-14 11:21:05,041:INFO:root: Processing batch at start index 3440 (num ids = 10)\n",
      "2019-03-14 11:21:10,590:INFO:root: Processing batch at start index 3450 (num ids = 10)\n",
      "2019-03-14 11:21:14,462:INFO:root: Processing batch at start index 3460 (num ids = 10)\n",
      "2019-03-14 11:21:17,272:INFO:root: Processing batch at start index 3470 (num ids = 10)\n",
      "2019-03-14 11:21:23,372:INFO:root: Processing batch at start index 3480 (num ids = 10)\n",
      "2019-03-14 11:21:27,362:INFO:root: Processing batch at start index 3490 (num ids = 10)\n",
      "2019-03-14 11:21:33,334:INFO:root: Collection complete (num failures = 25)\n"
     ]
    }
   ],
   "source": [
    "output_file = osp.join(DATA_DIR, 'articles', 'data.csv')\n",
    "![ -e $output_file ] && rm $output_file\n",
    "\n",
    "# Efetch docs: https://www.ncbi.nlm.nih.gov/books/NBK25499/#chapter4.EFetch\n",
    "# Get doc details: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=212403\n",
    "# 124720 results as of 2019-03-11\n",
    "# Test single article: \n",
    "#query = '5360497'\n",
    "query = '(human) AND ((t cell) OR (t lymphocyte)) AND (cytokine) AND ((differentiate) OR (differentiation) OR (differentiated)) AND ((polarization) OR (polarize) OR (induce) OR (induction))'\n",
    "collect(\n",
    "    query, output_file, \n",
    "    start_index=0, batch_size=10, max_failures=1000000,\n",
    "    batch_limit=350\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 3500 entries, 0 to 3499\n",
      "Data columns (total 6 columns):\n",
      "abstract    3481 non-null object\n",
      "date        2155 non-null object\n",
      "has_text    3500 non-null bool\n",
      "id          3500 non-null int64\n",
      "title       3500 non-null object\n",
      "xml         3500 non-null object\n",
      "dtypes: bool(1), int64(1), object(4)\n",
      "memory usage: 140.2+ KB\n"
     ]
    }
   ],
   "source": [
    "df = pd.read_csv(output_file)\n",
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "False    1766\n",
       "True     1734\n",
       "Name: has_text, dtype: int64"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df['has_text'].value_counts()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
